apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-carrier
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-carrier
  chart:
    git: ssh://git@github.com/c-dineshkumar/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net.org3ambr.fab.cluster4.aws.bafevent.com:8443
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a44fdf72fc78111eaae3f0a4fb79d321-228185970.ap-south-1.elb.amazonaws.com:9000
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.org1ambr.fab.cluster4.aws.bafevent.com:8443
    anchorstx: |-
      Ct8CChgKFggCGgYIg4nn+AUiCmFsbGNoYW5uZWwSwgIKvwIKCmFsbGNoYW5uZWwSYxJhCgtBcHBs
      aWNhdGlvbhJSCAESTgoKY2Fycmllck1TUBJAGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0
      ZXJzEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSABrLARLIAQoLQXBwbGljYXRpb24SuAEI
      ARKzAQoKY2Fycmllck1TUBKkAQgBGlgKC0FuY2hvclBlZXJzEkkSPwo9CjhwZWVyMC5jYXJyaWVy
      LW5ldC5vcmczYW1ici5mYWIuY2x1c3RlcjQuYXdzLmJhZmV2ZW50LmNvbRD7QRoGQWRtaW5zGgcK
      A01TUBIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSACIPCgtFbmRvcnNlbWVudBIAIgsKB1JlYWRl
      cnMSACoGQWRtaW5z

