apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: carrier-restserver
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/fabric-restserver
    git: ssh://git@github.com/c-dineshkumar/blockchain-automation-framework.git
    ref: develop
  releaseName: carrier-restserver
  values:
    metadata:
      namespace: carrier-net
    server:
      name: carrier-restserver
      port: 20001
      localmspid: carrierMSP
      image: index.docker.io/hyperledgerlabs/supplychain_fabric:rest_server_latest
      username: admin
      cert_path: "/secret/tls/admin.cert"
      key_path: "/secret/tls/admin.pem"
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    vault:
      address: http://a44fdf72fc78111eaae3f0a4fb79d321-228185970.ap-south-1.elb.amazonaws.com:9000
      role: vault-role
      authpath: carrier-net-auth
      secretprefix: secret/crypto/peerOrganizations/carrier-net
      serviceaccountname: vault-auth
      imagesecretname: regcred
      image: hyperledgerlabs/alpine-utils:1.0
    service:
      servicetype: ClusterIP
      ports:
        apiPort: 20001
        targetPort: 8000
    connection:
      peer: peer0.carrier-net
      peerAddress: peer0.carrier-net
      peerPort: 7051
      ordererAddress: orderer1.org1ambr.fab.cluster4.aws.bafevent.com
      ordererPort: 8443