apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: join-allchannel-store-peer0
  namespace: store-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: join-allchannel-store-peer0
  chart:
    git: ssh://git@github.com/c-dineshkumar/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: store-net
      images:
        fabrictools: hyperledger/fabric-tools:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.store-net.org3ambr.fab.cluster4.aws.bafevent.com:8443
      localmspid: storeMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a44fdf72fc78111eaae3f0a4fb79d321-228185970.ap-south-1.elb.amazonaws.com:9000
      authpath: store-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/store-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/store-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.org1ambr.fab.cluster4.aws.bafevent.com:8443

