apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: warehouse-expressapi
  namespace: warehouse-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/expressapp
    git: "ssh://git@github.com/c-dineshkumar/blockchain-automation-framework.git"
    ref: "develop"
  releaseName: warehousefabric-expressapi
  values:
    nodeName: warehouse-expressapi
    metadata:
      namespace: warehouse-net
    replicaCount: 1
    expressapp:
      serviceType: ClusterIP
      image: index.docker.io/hyperledgerlabs/supplychain_fabric:express_app_latest
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        apiUrl: http://warehouse-restserver.warehouse-net:20001/api/v1
    proxy:
      provider: haproxy
      name: warehouse
      type: fabric
      external_url_suffix: org2ambr.fab.cluster4.aws.bafevent.com
      peer_name: peer0
